name: 🐞 Bug Report
description: Report a reproducible issue or unexpected behavior in GoDarda
labels: [bug, needs-triage]
assignees:
  - shubhamrdarda
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the form below to help us fix it faster.

  - type: input
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll to '...'
        4. See error
    validations:
      required: true

  - type: input
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (if applicable)
      description: Drag and drop images or paste links here.

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Desktop
        - Smartphone
        - Both

  - type: textarea
    id: environment
    attributes:
      label: Environment details
      placeholder: |
        - OS: [e.g. Windows 11]
        - Browser: [e.g. Chrome]
        - App Version: [e.g. 1.2.3]

  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Logs, error messages, or anything else helpful.