name: GDID Tracker  # Runs GDID tracking script and auto-generates PR if gdid.txt changes

on:
  push:
    branches:
      - main  # Trigger workflow on every push to the main branch

jobs:
  track-gdid:
    name: Track GDID Usage
    runs-on: ubuntu-latest

    # Expose whether gdid.txt was modified so downstream jobs can act conditionally
    outputs:
      changed: ${{ steps.detect_changes.outputs.changed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5  # Fetch the latest code from the main branch

      - name: Set up Python
        uses: actions/setup-python@v5  # Ensure Python is available in the runner
        with:
          python-version: '3.13'  # Use the latest stable Python version

      - name: Run GDID Tracker
        run: python assets/gdid.py  # Execute the Python script that updates gdid.txt

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"  # Set bot identity for commits
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Detect changes in gdid.txt
        id: detect_changes
        run: |
          # Skip PR creation if gdid.txt doesn't exist
          if [ ! -f assets/gdid.txt ]; then
            echo "gdid.txt not found — skipping PR creation"
            echo "changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Stage gdid.txt and check for changes
          git add assets/gdid.txt
          echo "Staged diff for gdid.txt:"
          git diff --cached -- assets/gdid.txt

          # Set output flag based on whether changes were detected
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

  create-pr:
    name: Create Pull Request
    needs: track-gdid  # Run only after GDID tracking job completes
    if: needs.track-gdid.outputs.changed == 'true'  # Trigger only if gdid.txt was modified
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5  # Required again because each job runs in a fresh environment

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5  # Automate PR creation for updated gdid.txt
        with:
          commit-message: Auto-update gdid.txt
          title: Auto-update gdid.txt
          body: |
            This PR was created automatically by the GDID Tracker workflow.
            It includes updates to gdid.txt based on new usage references.
            If everything looks good, feel free to merge and the branch will auto-delete.
          branch: gdid-update-${{ github.run_id }}
          delete-branch: true  # Clean up branch after merge or close