name: GDID PR Creator

on:
  push:
    branches:
      - develop
    paths:
      - .trigger-pr

jobs:
  create-pr:
    name: Create Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Remove trigger file and push cleanup
        run: |
          # Remove from disk
          rm -f .trigger-pr

          # Remove from Git index if present
          if git ls-files --error-unmatch .trigger-pr > /dev/null 2>&1; then
            git rm .trigger-pr
            git commit -m "Clean up trigger file before PR"
            git push origin develop
          else
            echo "Trigger file already removed or not tracked"
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Auto-update GDID sets
          title: Auto-update GDID sets
          body: |
            This PR was created automatically by the GDID Tracker workflow.
            It includes updates to gdid_set*.txt and invalid.txt based on new usage references.
            Please review and merge manually into develop.
          branch: gdid-update-${{ github.run_id }}
          base: develop
          labels: automated, gdid-update