name: Setup Environment and Automated Tests
on:
  schedule:
    - cron: '30 2 25 * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
      - name: Setup Environment
        run: python3 setup.py full
      - name: Run Automated Tests
        run: python3 tests/run.py
