name: Setup Environment and Automated Tests

# Trigger the workflow on the 25th of every month at 11:30 UTC
on:
  schedule:
    - cron: '30 11 25 * *'
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Prevents hanging jobs

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Step 3: Setup Java environment
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      # Step 4: Run setup script with error handling
      - name: Setup Environment
        run: |
          set -e  # Exit immediately if any command fails
          echo "Starting environment setup..."
          python3 setup.py full
        shell: bash

      # Step 5: Run automated tests with error handling
      - name: Run Automated Tests
        run: |
          set -e
          echo "Running tests..."
          python3 tests/run.py
        shell: bash