name: Auto Reset Develop After Squash Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  reset-develop:
    if: github.event.pull_request.merged == true &&
        github.event.pull_request.head.ref == 'develop' &&
        github.event.pull_request.user.login == 'shubhamrdarda'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v5
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GoDarda Bot"
          git config user.email "bot@godarda.dev"

      - name: Fetch all branches
        run: git fetch origin

      - name: Reset develop to match main
        run: |
          git checkout develop || git checkout -b develop
          git reset --hard origin/main
          git push origin develop --force-with-lease

      - name: Log reset message
        run: echo "GoDarda squash complete. 'develop' has been reset to match 'main'."